Upgrade ember
ciena-blueplanet/ember-pollboy pull request #40
Opened 2017-06-26 17:48 UTC by helloWorldCindy

**This project uses [semver](http://semver.org), please check the scope of this pr:**

- [ ] #none# - documentation fixes and/or test additions
- [ ] #patch# - backwards-compatible bug fix
- [x] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG

Upgrade Ember-cli to 2.12.3

2017-06-26 18:14 UTC, notmessenger requested changes

2017-06-26 18:14 UTC, notmessenger commented on bower.json
> +    "ember": "^2.12.2",
Aren't we now using `npm`s `ember-source`?  This should't be needed.

2017-06-26 18:14 UTC, notmessenger commented on package.json
> +    "ember-cli": "^2.12.3",
Remove the `^` - we're locking this dependency down.

2017-06-26 18:14 UTC, notmessenger commented on package.json
>      "broccoli-asset-rev": "^2.5.0",
Change to `^2.4.5` to be consistent with what `ember-cli` is currently at and with the other repos doing the same.

2017-06-26 18:14 UTC, notmessenger commented on package.json
>      "ember-cli-app-version": "^2.0.1",
Remove this dependency

2017-06-26 18:14 UTC, notmessenger commented on tests/index.html
> +    <script src="/testem.js" integrity=""></script>
this should be the first `<script>` tag in this group

2017-06-26 18:14 UTC, notmessenger commented on tests/helpers/start-app.js
>  import config from '../../config/environment'
The entire contents of this file should be:

```
import Ember from 'ember'
const {merge, run} = Ember

import Application from '../../app'
import config from '../../config/environment'

export default function startApp (attrs) {
  let attributes = merge({}, config.APP)
  attributes = merge(attributes, attrs) // use defaults, but you can override;

  return run(() => {
    let application = Application.create(attributes)
    application.setupForTesting()
    application.injectTestHelpers()
    return application
  })
}
```

2017-06-26 18:16 UTC, notmessenger commented
These modifications need to be made to the _package.json_ file:

*change these packages to these values*
"ember-cli-htmlbars-inline-precompile": "^0.3.6"
"ember-cli-inject-live-reload": "^1.4.1"
"ember-export-application-global": "^1.0.5"
"ember-load-initializers": "^0.6.0"

*add these packages*
"ember-cli-shims": "^1.0.2"
"ember-source": "~2.12.0"

*remove these packages*
"ember-disable-proxy-controllers": "^1.0.1"

2017-06-26 18:38 UTC, helloWorldCindy commented on bower.json
> +    "ember": "^2.12.2",
Fixed.

2017-06-26 18:38 UTC, helloWorldCindy commented on package.json
>      "broccoli-asset-rev": "^2.5.0",
Fixed.

2017-06-26 18:38 UTC, helloWorldCindy commented on package.json
> +    "ember-cli": "^2.12.3",
Fixed.

2017-06-26 18:38 UTC, helloWorldCindy commented on package.json
>      "ember-cli-app-version": "^2.0.1",
Fixed.

2017-06-26 18:38 UTC, helloWorldCindy commented on tests/index.html
> +    <script src="/testem.js" integrity=""></script>
Fixed.

2017-06-26 18:40 UTC, helloWorldCindy commented on tests/helpers/start-app.js
>  import config from '../../config/environment'
aren't they the same?

2017-06-26 18:43 UTC, notmessenger commented on tests/helpers/start-app.js
>  import config from '../../config/environment'
Oops, sorry, yes they are.  Not sure what I was looking at.

2017-06-26 18:48 UTC, notmessenger commented
Url in _.gitignore_ should be

```
-# See http://help.github.com/ignore-files/ for more about ignoring files.
+# See https://help.github.com/ignore-files/ for more about ignoring files.
```

2017-06-27 13:33 UTC, juwara0 commented on .eslintrc.js
> +  extends: ['frost-standard'],
This line should not have the array brackets but instead be:

`extends: 'frost-standard',`

2017-06-27 15:04 UTC, helloWorldCindy commented on .eslintrc.js
> +  extends: ['frost-standard'],
Fixed.

2017-07-07 15:56 UTC, dafortin commented on .travis.yml
> -  - EMBER_TRY_SCENARIO=ember-1-12
@juwara0 do we need `firefox: 'latest-esr'`

2017-07-07 15:56 UTC, dafortin commented on .travis.yml
> +  - env: EMBER_TRY_SCENARIO=ember-release
we don't need `release` if it's not in the run matrix

2017-07-07 15:57 UTC, dafortin commented on bower.json
>      "ember-mocha-adapter": "~0.3.1"
No necessary.

2017-07-07 15:59 UTC, dafortin commented on tests/.eslintrc
> -{}
remove this file

2017-07-07 17:14 UTC, helloWorldCindy commented on tests/.eslintrc
> -{}
@dafortin Do you know why this file will show up here? I can't find this file in my local copy.

2017-07-07 17:16 UTC, helloWorldCindy commented on bower.json
>      "ember-mocha-adapter": "~0.3.1"
Fixed.

2017-07-07 17:16 UTC, helloWorldCindy commented on .travis.yml
> +  - env: EMBER_TRY_SCENARIO=ember-release
Fixed.

2017-07-07 17:29 UTC, dafortin commented on tests/.eslintrc
> -{}
I'm not sure.

2017-07-10 12:48 UTC, juwara0 commented on package.json
>      "ember-cli-test-loader": "^1.1.1",
This should be removed.

2017-07-10 12:48 UTC, juwara0 commented on package.json
>      "ember-resolver": "^2.1.1",
This should be: `"ember-resolver": "^2.0.3",`

2017-07-10 12:48 UTC, juwara0 commented on tests/.eslintrc.js
> +};
Please remove the semicolon

2017-07-10 12:48 UTC, juwara0 commented on .travis.yml
> -  - EMBER_TRY_SCENARIO=ember-1-12
No, it can be removed. I have this listed as a task in the dev ops project to do across all the repos.

2017-07-10 12:48 UTC, juwara0 commented on .travis.yml
> -  - EMBER_TRY_SCENARIO=ember-1-12
Fixed

2017-07-10 12:48 UTC, juwara0 commented on package.json
>      "ember-cli-test-loader": "^1.1.1",
Fixed

2017-07-10 12:48 UTC, juwara0 commented on package.json
>      "ember-resolver": "^2.1.1",
FIXED

2017-07-10 12:48 UTC, juwara0 commented on tests/.eslintrc.js
> +};
FIXED

2017-07-10 16:05 UTC, notmessenger approved these changes

2017-07-10 16:06 UTC, notmessenger commented
👍

2017-07-10 16:17 UTC, juwara0 commented
Approved.

2017-07-10 16:18 UTC, merged